-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-11-05 19:40:37 BRT
--   site:      SQL Server 2012
--   tipo:      SQL Server 2012



CREATE TABLE BENEFICIARIOS 
    (
     COD_TIB INTEGER NOT NULL , 
     NUMCAD_PES INTEGER NOT NULL 
    )
;

CREATE TABLE COMPOSICAO_FAMILIAR 
    (
     NUMCAD_BEN INTEGER NOT NULL , 
     NUMCAD_FAM INTEGER NOT NULL , 
     COD_GPA INTEGER NOT NULL 
    )
;

ALTER TABLE COMPOSICAO_FAMILIAR ADD CONSTRAINT COMPOSICAO_FAMILIAR_PK PRIMARY KEY  (NUMCAD_BEN, NUMCAD_FAM)
;

CREATE TABLE GRAU_PARENTESCO 
    (
     COD_GPA INTEGER NOT NULL , 
     DESC_GPA VARCHAR (50) NOT NULL 
    )
;

ALTER TABLE GRAU_PARENTESCO ADD CONSTRAINT GRAU_PARENTESCO_PK PRIMARY KEY  (COD_GPA)
;

CREATE TABLE HOSPITAL 
    (
     COD_HOS INTEGER NOT NULL , 
     NOME_HOS VARCHAR (100) NOT NULL 
    )
;

ALTER TABLE HOSPITAL ADD CONSTRAINT HOSPITAL_PK PRIMARY KEY  (COD_HOS)
;

CREATE TABLE MUNICIPIO 
    (
     COD_MUN INTEGER NOT NULL , 
     NOME_MUN VARCHAR (100) NOT NULL , 
     COD_UF INTEGER NOT NULL 
    )
;

ALTER TABLE MUNICIPIO ADD CONSTRAINT MUNICIPIO_PK PRIMARY KEY  (COD_MUN)
;

CREATE TABLE PESSOAS 
    (
     NUMCAD_PES INTEGER NOT NULL , 
     TIPO_PES VARCHAR (1) NOT NULL , 
     DATACAD_PES DATE , 
     NOME_PES VARCHAR (100) NOT NULL , 
     RG_PES VARCHAR (20) , 
     CPF_PES VARCHAR (20) , 
     SEXO_PES VARCHAR (1) , 
     DATANASC_PES DATE , 
     ENDERECO_PES VARCHAR (100) , 
     BAIRRO_PES VARCHAR (50) , 
     CEP_PES VARCHAR (10) , 
     FONE_PES VARCHAR (50) , 
     EMAIL_PES VARCHAR (50) , 
     PROFISSAO_PES VARCHAR (100) , 
     PATOLOGIA_PES VARCHAR (50) , 
     MATRICULA_HOSP_PES VARCHAR (20) , 
     MEDICAMENTO_PES VARCHAR (250) , 
     FLAG_FUMANTE_PES BIT , 
     OBSERVACOES_PES TEXT , 
     COD_REL INTEGER , 
     COD_RAC INTEGER , 
     COD_MUN INTEGER , 
     COD_HOS INTEGER 
    )
;

ALTER TABLE PESSOAS ADD CONSTRAINT PESSOAS_PK PRIMARY KEY  (NUMCAD_PES)
;

CREATE TABLE RACA 
    (
     COD_RAC INTEGER NOT NULL , 
     DESC_RAC VARCHAR (100) 
    )
;

ALTER TABLE RACA ADD CONSTRAINT RACA_PK PRIMARY KEY  (COD_RAC)
;

CREATE TABLE RELIGIAO 
    (
     COD_REL INTEGER NOT NULL , 
     DESC_REL VARCHAR (100) 
    )
;

ALTER TABLE RELIGIAO ADD CONSTRAINT RELIGIAO_PK PRIMARY KEY  (COD_REL)
;

CREATE TABLE RESPONSAVEIS 
    (
     NUMCAD_BEN INTEGER NOT NULL , 
     NUMCAD_RES INTEGER NOT NULL , 
     COD_GPA INTEGER NOT NULL 
    )
;

ALTER TABLE RESPONSAVEIS ADD CONSTRAINT RESPONSAVEIS_PK PRIMARY KEY  (NUMCAD_BEN, NUMCAD_RES)
;

CREATE TABLE TIPO_BENEFICIO 
    (
     COD_TIB INTEGER NOT NULL , 
     DESC_TIB VARCHAR (50) NOT NULL 
    )
;

ALTER TABLE TIPO_BENEFICIO ADD CONSTRAINT TIPO_BENEFICIO_PK PRIMARY KEY  (COD_TIB)
;

CREATE TABLE UF 
    (
     COD_UF INTEGER NOT NULL , 
     NOME_UF VARCHAR (50) NOT NULL 
    )
;

ALTER TABLE UF ADD CONSTRAINT UF_PK PRIMARY KEY  (COD_UF)
;

ALTER TABLE BENEFICIARIOS 
    ADD CONSTRAINT BENEFICIARIOS_PESSOAS_FK FOREIGN KEY 
    ( 
     NUMCAD_PES
    ) 
    REFERENCES PESSOAS 
    ( 
     NUMCAD_PES 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE BENEFICIARIOS 
    ADD CONSTRAINT BENEFICIARIOS_TIPO_BENEFICIO_FK FOREIGN KEY 
    ( 
     COD_TIB
    ) 
    REFERENCES TIPO_BENEFICIO 
    ( 
     COD_TIB 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE COMPOSICAO_FAMILIAR 
    ADD CONSTRAINT COMPOSICAO_FAMILIAR_GRAU_PARENTESCO_FK FOREIGN KEY 
    ( 
     COD_GPA
    ) 
    REFERENCES GRAU_PARENTESCO 
    ( 
     COD_GPA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE COMPOSICAO_FAMILIAR 
    ADD CONSTRAINT COMPOSICAO_FAMILIAR_PESSOAS_FK FOREIGN KEY 
    ( 
     NUMCAD_BEN
    ) 
    REFERENCES PESSOAS 
    ( 
     NUMCAD_PES 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE COMPOSICAO_FAMILIAR 
    ADD CONSTRAINT COMPOSICAO_FAMILIAR_PESSOAS_FKv2 FOREIGN KEY 
    ( 
     NUMCAD_FAM
    ) 
    REFERENCES PESSOAS 
    ( 
     NUMCAD_PES 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE MUNICIPIO 
    ADD CONSTRAINT MUNICIPIO_UF_FK FOREIGN KEY 
    ( 
     COD_UF
    ) 
    REFERENCES UF 
    ( 
     COD_UF 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE PESSOAS 
    ADD CONSTRAINT PESSOAS_HOSPITAL_FK FOREIGN KEY 
    ( 
     COD_HOS
    ) 
    REFERENCES HOSPITAL 
    ( 
     COD_HOS 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE PESSOAS 
    ADD CONSTRAINT PESSOAS_MUNICIPIO_FK FOREIGN KEY 
    ( 
     COD_MUN
    ) 
    REFERENCES MUNICIPIO 
    ( 
     COD_MUN 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE PESSOAS 
    ADD CONSTRAINT PESSOAS_RACA_FK FOREIGN KEY 
    ( 
     COD_RAC
    ) 
    REFERENCES RACA 
    ( 
     COD_RAC 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE PESSOAS 
    ADD CONSTRAINT PESSOAS_RELIGIAO_FK FOREIGN KEY 
    ( 
     COD_REL
    ) 
    REFERENCES RELIGIAO 
    ( 
     COD_REL 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE RESPONSAVEIS 
    ADD CONSTRAINT RESPONSAVEIS_GRAU_PARENTESCO_FK FOREIGN KEY 
    ( 
     COD_GPA
    ) 
    REFERENCES GRAU_PARENTESCO 
    ( 
     COD_GPA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE RESPONSAVEIS 
    ADD CONSTRAINT RESPONSAVEIS_PESSOAS_FK FOREIGN KEY 
    ( 
     NUMCAD_BEN
    ) 
    REFERENCES PESSOAS 
    ( 
     NUMCAD_PES 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;

ALTER TABLE RESPONSAVEIS 
    ADD CONSTRAINT RESPONSAVEIS_PESSOAS_FKv1 FOREIGN KEY 
    ( 
     NUMCAD_RES
    ) 
    REFERENCES PESSOAS 
    ( 
     NUMCAD_PES 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
;



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
