CREATE TABLE DOADORES (
  COD_DOA   SERIAL PRIMARY KEY,
  NOME_DOA  VARCHAR(200) NOT NULL,
  EMAIL_DOA VARCHAR(150),
  FONE_DOA  VARCHAR(20),
  CPF_CNPJ  VARCHAR(20),
  TIPO_DOA  VARCHAR(10) NOT NULL DEFAULT 'PF' CHECK (TIPO_DOA IN ('PF','PJ')),
  DATA_CAD  DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE INDEX idx_doadores_nome ON DOADORES (LOWER(NOME_DOA));

CREATE TABLE DOACOES (
  COD_DOC          SERIAL PRIMARY KEY,
  COD_DOA          INTEGER NOT NULL REFERENCES DOADORES(COD_DOA),
  DT_DOC           DATE NOT NULL,
  TIPO_DOC         VARCHAR(50) NOT NULL CHECK (TIPO_DOC IN ('Alimentos','Roupas','Dinheiro','Outros')),
  DESCRICAO_DOC    TEXT,
  OBS_DOC          TEXT,
  DATA_CRIACAO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_doacoes_data ON DOACOES (DT_DOC);
CREATE INDEX idx_doacoes_doador ON DOACOES (COD_DOA);

CREATE TABLE DOACAO_ITENS (
  COD_DOC INTEGER NOT NULL REFERENCES DOACOES(COD_DOC) ON DELETE CASCADE,
  COD_ITE INTEGER NOT NULL REFERENCES ITENS_CESTA(COD_ITE),
  QTD     INTEGER NOT NULL CHECK (QTD > 0),
  PRIMARY KEY (COD_DOC, COD_ITE)
);

ALTER TABLE ESTOQUE_MOV
  ADD COLUMN COD_DOC INTEGER NULL REFERENCES DOACOES(COD_DOC) ON DELETE SET NULL;
CREATE INDEX idx_estoque_mov_doc ON ESTOQUE_MOV (COD_DOC);
